### ISSUE TITLE
README summary is broken

### ISSUE THREAD

**Issue by icaraps** [adobe/aio-theme#1162]
<img width="760" alt="Screen Shot 2022-10-27 at 6 12 41 PM" src="https://user-images.githubusercontent.com/6012307/198343316-67ac0830-e162-4672-b6de-88885818d279.png">

**Comment by timkim** [comment]
Fixed:
https://github.com/adobe/aio-theme/commit/d4cf8e80336cf92987fcb3f829c16dac08dbb502
