### ISSUE TITLE
Regression: heading underline and anchor is weird

### ISSUE THREAD

**Issue by icaraps** [adobe/aio-theme#1163]
Before: 
<img width="1033" alt="Screen Shot 2022-10-27 at 6 18 57 PM" src="https://user-images.githubusercontent.com/6012307/198345667-0da13a30-ad26-4080-bec8-c497b97903ea.png">

Now: 
<img width="1038" alt="Screen Shot 2022-10-27 at 6 22 12 PM" src="https://user-images.githubusercontent.com/6012307/198345638-6ff9db87-752d-4450-a3e2-769baf77a21a.png">

**Comment by timkim** [comment]
This was from the upgrade to spectrum-css so the heading underline now looks like that as with the blue anchor colour. I actually didn't noticed that the anchor became an icon. Seem to have come from this commit: https://github.com/adobe/aio-theme/commit/110a9bf1ab0e9998b7a58ab03ee1760ad4c76821#diff-c6ed490f4e083aa4c947c76c22b2cd960a64feec549d35f6fc0fc7a3860b6446R115. 

I don't think that the # becoming an icon is an issue.
