### ISSUE TITLE
Regression: double console button on mobile

### ISSUE THREAD

**Issue by icaraps** [adobe/aio-theme#1164]
Before: 
<img width="517" alt="Screen Shot 2022-10-27 at 6 19 28 PM" src="https://user-images.githubusercontent.com/6012307/198345933-f72094b6-0421-40ab-8b7d-93aedb732b5d.png">

Now:
<img width="517" alt="Screen Shot 2022-10-27 at 6 21 53 PM" src="https://user-images.githubusercontent.com/6012307/198345947-f31b43a6-4638-43c6-88bd-0074aef2cd3e.png">

**Comment by timkim** [comment]
We're re-working the nav for mobile now so this issue should be fixed shortly...

**Comment by timkim** [comment]
Should be fixed in the latest theme now.
