### ISSUE TITLE
Code syntax highlighting for more languages

### ISSUE THREAD

**Issue by timkimadobe** [adobe/aio-theme#1390]
# 🙋 Feature Request

Hi Adobe I/O team, it would be awesome if code syntax highlighting/styling was available for more languages, for example:
* Java (doesn't seem to be available currently?)
* Kotlin
* Swift
* Bash
* etc.

With different highlighting for:
1. Access modifier & keywords (ex: public, private, static, final, function, if, else, etc.)
2. Data types (ex: void, String, Bool, Map<String, Object>)
3. Function/method names (ex: myFoo(), class.someBar())
4. Variables
5. Classes
6. Annotations (ex: @JvmStatic, @JvmOverloads, @available(macOS 10.15, *), etc.)

## 🤔 Expected Behavior

For example, in Android Studio the following code styling helps make it more visually understandable:
<img width="784" alt="Screen Shot 2023-02-16 at 3 25 14 PM" src="https://user-images.githubusercontent.com/95260439/219510623-2d4fab1c-84b9-4d42-b234-39711f84cf74.png">

Gitbook example:  

<img width="571" alt="Screen Shot 2023-02-16 at 3 28 09 PM" src="https://user-images.githubusercontent.com/95260439/219511053-04b0afaa-b586-479f-93f7-956913de1295.png">

https://aep-sdks.gitbook.io/docs/foundation-extensions/consent-for-edge-network/api-reference#updateconsents

## 😯 Current Behavior

<img width="568" alt="Screen Shot 2023-02-16 at 3 29 14 PM" src="https://user-images.githubusercontent.com/95260439/219511122-cfa5ba6a-751b-4cc6-91e8-b35b966a29b2.png">

https://developer.adobe.com/client-sdks/documentation/consent-for-edge-network/api-reference/#updateconsents

## 💁 Possible Solution

Potentially using a library with support for a ton of languages like: https://github.com/highlightjs/highlight.js

## 🔦 Context

For the Adobe I/O docs for the Mobile SDK, code syntax and examples are a crucial part of the developer experience and code highlighting for all the languages we support would greatly improve readability:

https://developer.adobe.com/client-sdks/documentation/mobile-core/api-reference/

## 🧢 Your Company/Team

Adobe/Experience Platform Mobile SDK

**Comment by timkim** [comment]
Hey @timkimadobe ,

Ya the prism syntax highlighter only comes with some code options as default. Java not being one of them is kinda weird. We can add more support.

**Comment by timkim** [comment]
Oop forgot to update this issue but more langs have been added with this commit and should be on the latest version of the theme (4.9.8 and above):
https://github.com/adobe/aio-theme/commit/3d24836c4476d925b5d458ed06a5bae6a54f42b2
