### ISSUE TITLE
Minor fix for clean instructions

### ISSUE THREAD

**Issue by sean-parent** [adobe/aio-theme#1494]
# 🙋 Documentation Request

The instructions to force a full rebuild in the readme are incorrect:

```bash
yarn clean && yarn cache clean && rm node_modules && rm yarn.lock
```

should be:

```bash
yarn clean && yarn cache clean && rm -r node_modules && rm yarn.lock
```
Otherwise, the `rm node_module` will fail because `node_modules` is a directory and the `yarn.lock` file will not be removed.

## 🧢 Your Company/Team

Adobe/STLab

**Comment by timkim** [comment]
Fixed here: https://github.com/adobe/aio-theme/commit/0a4126f2627add892aee7d86f0b8f0c0ccfb6fe9
