### ISSUE TITLE
README Questions

### ISSUE THREAD

**Issue by macdonst** [adobe/aio-theme#15]
1. In Using the Adobe I/O CLI it talks about passing a template option to the aio cli to use a different template. We really don’t want customers using a different template for the website right?
2. The part about Adding a Path Prefix will become very important when a bunch of microsites are combined into the one uber site. Gatsby navigation won’t work correctly if the path prefix is not right.
3. For the Content Structure we only show folders with index.md in them. Since lots of teams will be porting markdown files from pre-existing doc repos they will have names like JWTCertificate.md so we should make it plain that they don’t need to rename every file to index.md and put in in a directory called jwt_certificate.
4. In Front Matter Support we mention adding a title to the page but we also have the title in gatsby-config.js. Do we need the title in both places? This will become important for the search functionality.
5. For Specifying external contributors what does the url point to? Is it just an image file? I guess I’m a little confused how this is supposed to work.
6. We may have to change the way OpenAPI spec are defined. If we end up doing a full site search then we’ll need to add the spec to the search index. I will propose we have a list of OpenAPI specs that should be added to the site which can be local to the project or remote via http. Then we can updated the Gatsby-node.js file to read the list and create all the pages.
7. I forgot to ask before but why do we need to add jsDoc: true to frontmatter?
8. Do we even want to mention Customizations? We don’t actually want people messing with the Code or Button components do we?

**Comment by icaraps** [comment]
1) As per design, there are 3 templates: documentation, platform and product. We could present only the 3 options in the CLI if passing a parameter is a problem cc @shazron .
4) I can imagine the label shown in the GlobalHeader can be different from the <title> in document.  
5) Currently it's just the user Github profile URL.
7) That's just a matter of optimization. 
8) If a team chooses to diverge from the standard template for whatever reason then this should be easy and possible – ie if they want to maintain their own rendering templates then this needs to be part of our setup.
