### ISSUE TITLE
Table body errors when providing a single element

### ISSUE THREAD

**Issue by mbradoschi** [adobe/aio-theme#1518]
# 🐛 Bug Report 

`TBody` component will throw a `TypeError` whenever the children provided to it represent a single item array.

E.g.:

```
<TBody>
  {singleItemArray.map(item => <Tr />)}
</TBody>
```

## 🤔 Expected Behavior

`TBody` should properly display provided children or be empty when none provided.

## 😯 Current Behavior

Component errors with:

`Uncaught (in promise) TypeError: Cannot set properties of undefined (setting 'tableWidth')`

## 💁 Possible Solution

#1517 

## 🔦 Context

Breaking change after aio-theme upgrade inside https://github.com/AdobeDocs/cloudmanager-api-docs.

## 💻 Code Sample

https://github.com/AdobeDocs/cloudmanager-api-docs/blob/main/src/components/playground/link-table.js#L67

## 🌍 Your Environment

Production

## 🧢 Your Company/Team

AEM Cloud Manager

## 🕷 Tracking Issue (optional)

**Comment by dmitrymatio** [comment]
This was fixed with https://github.com/adobe/aio-theme/pull/1521 sorry for missing tag 🙏
