### ISSUE TITLE
Known markdown parser crashers

### ISSUE THREAD

**Issue by ashryanbeats** [adobe/aio-theme#19]
This might be a good place to collect markdown/markup FAQs to be documented in the readme.

To start, I've noticed that unclosed `<br>` tags will crash the parser. Self-closed tags work as expected: `<br/>`.

**Comment by icaraps** [comment]
That's because the parser is based on JSX and JSX doesn't allow non closed tags.

**Comment by chuckweger** [comment]
Errors like '"gatsby-plugin-mdx" threw an error while running the onCreatePage lifecycle:' are probably helpful to Gatsby developers with the source code, but are not helpful to content writers trying to figure out why things are failing. Putting the offending .md file (or config file) into the error message would be super helpful.

**Comment by bdenham** [comment]
Hey @chuckweger, I'm working on a solution to this issue now. As @icaraps said, when you have HTML tags that are not closed within your markdown files (such as, `<br>`, `<hr>`, `<image>`), the parser will not recognize these tags as proper JSX, which will throw the error. Where are the docs (what repo) you are parsing? I can take a look and let you know which tags and files are causing the problem.

@ashryanbeats, yes, along with my fix, I'll create documentation about which tags the fix closes so writers can get in the habit of not including open HTML tags in their markdown.

**Comment by chuckweger** [comment]
Hi @bdenham, thanks for the quick reply. I fixed this one myself. It turned out that I had used the old <b>something</b> syntax, which Gatsby for sure does not like. Changing it to **something** worked.

**Comment by chuckweger** [comment]
Wow, I should have quoted parts of that reply (forgot this uses markdown). Let's try again.
I formerly used:

```
<b>something</b>
```

but am now using

```
**something**
```

**Comment by bdenham** [comment]
Yeah, making sure everything in a markdown file is actually markdown is definitely a process. Takes time when working through legacy markdown to ensure that the loose HTML tags are either replaced by their markdown equivalents, closed, or removed.

**Comment by chuckweger** [comment]
Gatsby *does not* like local URLs with dashes.
For example:

```[look here](../code-samples/
```

 throws this error:

TypeError: undefined is not an object (evaluating '_allSitePage$nodes$fi.componentPath')

Changing this to

```
[look here](../code_samples/
```

Makes everything fine again.

**Comment by chuckweger** [comment]
Sheesh. I will never get the hang of posting comments in markdown syntax. Sorry!

OLD code that throws the error:

```
[look here](../code-samples/)
```

NEW CODE THAT WORKS:

```
look here](../code_samples/)
```

**Comment by bdenham** [comment]
Great. Keep them coming. I'm creating a markdown file for testing that will have your examples as well as several tags I know to check for. So your input here is a good a place as any to note your problem markdown. Thanks!

**Comment by icaraps** [comment]
```
<InlineAlert variant="info" slots="text"/>
While this documentation...
```

The parser is parsing the above markdown as [InlineAlert, String].

If you add a linebreak before the text:

```
<InlineAlert variant="info" slots="text"/>

While this documentation...
```

The parser is parsing it as [InlineAlert, Paragraph] which is what InlineAlert is expecting.

**Comment by bdenham** [comment]
Thanks, @icaraps. Yes, this applies for any JSX tag within an `.mdx` file or an `.md` file processed as MDX. That's what makes cleaning up an `.md` file that has `<br>` and `<hr>` tags so difficult. Because even if you close the invalid tags that break the build (using `<br/>`, `<hr/>`, etc), you still have to add line breaks to make the MDX parser render then as anything other than test strings. 

For example, if you have a second-level heading immediately following a closed break tag in your markdown:
```
<br/>
## Heading level 2
```
The MDX parser will treat the heading (## Heading level 2) -- or anything else! -- as text that is a part of the closed `<br/>` tag:
```
"type": "jsx",
"value": "<br/>\n## Heading level 2",
```
So in this case, the HTML output looks like this (with no tag wrapping the heading):
```
<br />
## Heading level 2
```

Instead what it should be:
```
    <br />
    <h2>Heading level 2</h2>
```

**Comment by bdenham** [comment]
I've got a draft PR for a new gatsby plugin in the parliament-client-template that fixes tags which cause know MDX/JSX parsing errors: adobe/parliament-client-template#36.

I can also create a node CLI for this as well, which could be run locally and committed to your docs repo on GitHub to fix the issues. Is there any interest in such a CLI?

**Comment by icaraps** [comment]
@bdenham sure we have a CLI so maybe just add it there https://github.com/adobe/aio-cli-plugin-doc ? Maybe as part of https://github.com/adobe/aio-cli-plugin-doc/issues/8 ?

**Comment by bdenham** [comment]
@icaraps Cool. I'll check it out. Thanks.

**Comment by icaraps** [comment]
https://github.com/AdobeDocs/dev-site-documentation-template/pull/81 should help to prevent these issues
