### ISSUE TITLE
Add an MDX validator to npm script

### ISSUE THREAD

**Issue by ashryanbeats** [adobe/aio-theme#25]
For details on core issue, see https://github.com/gatsbyjs/gatsby/issues/22135

It would be nice to bake a tool like this in to whatever npm script content authors are going to use.

**Comment by bdenham** [comment]
I've got a draft PR in the parliament-client-template that fixes tags that cause know MDX/JSX parsing errors: https://github.com/adobe/parliament-client-template/pull/36.

I think it's also a good idea to create node CLI for this as well that can be run locally on a GitHub docs repo.

**Comment by icaraps** [comment]
@bdenham  See my reply https://github.com/adobe/gatsby-theme-parliament/issues/19#issuecomment-709002477

**Comment by icaraps** [comment]
Fixed by https://github.com/AdobeDocs/dev-site-documentation-template/pull/81
