### ISSUE TITLE
Can I use this theme with an existing gatsby project？

### ISSUE THREAD

**Issue by chuchude** [adobe/aio-theme#893]
# ❔ Question

Hello there,

Can I use this theme with an existing gatsby project? or do I have to use a template for the initial setup?

Thank you
## 🔦 Context

I would like to use the Enhanced Markdown in the theme.

## 💻 Code Sample

I have installed the @adobe/gatsby-theme-aio@4.2.2 and added it to the gatsby-config.js plugin 
<code>  plugins: [ '@adobe/gatsby-theme-aio']
 </code>

**Comment by timkim** [comment]
Hi there @chuchude 

You won't be able to use this theme as it requires several secrets that are not sharable. You could fork it so that it doesn't require all the `.env` variables to run, but that's up to you.
