### ISSUE TITLE
Hero component displays scrollbar

### ISSUE THREAD

**Issue by jhadobe** [adobe/aio-theme#944]
# 🐛 Bug Report 

The Hero component displays a scroll bar at certain page widths/zoom levels.

## 🤔 Expected Behavior

The Hero block should display a fixed image or solid color and not scroll at any width.

## 😯 Current Behavior

At some unknown medium width, the hero image has an extraneous scrollbar. At a very narrow or wide width this scrollbar is not present.

<img width="953" alt="Screen Shot 2022-06-28 at 5 25 06 PM" src="https://user-images.githubusercontent.com/98363870/176537624-3ebeb49f-c105-4d13-9c14-a79a3219e105.png">

## 💁 Possible Solution

Maybe something in the CSS?

## 🔦 Context

Minor aesthetic issue.

## 💻 Code Sample

https://developer.adobe.com/commerce/webapi/

## 🌍 Your Environment

https://developer.adobe.com/commerce/webapi/

## 🧢 Your Company/Team

Commerce Documentation, but the bug affects all developer.adobe pages that use the hero block from what I've seen.

**Comment by timkim** [comment]
This doesn't look to be a problem anymore.
