### ISSUE TITLE
Inline alert image in repo readme broken

### ISSUE THREAD

**Issue by 317brian** [adobe/aio-theme#981]
# 🙋 Documentation Request

The inline alert image is broken in the repo readme. The link 404s: https://github.com/adobe/aio-theme/blob/main/docs/images/inline-alert-variants.png

**Comment by timkim** [comment]
Fixed. 
https://github.com/adobe/aio-theme/commit/70b192fd0fa39445e5b0be151b1ce3d1687f48e9#diff-b335630551682c19a781afebcf4d07bf978fb1f8ac04c6bf87428ed5106870f5R1377
