### ISSUE TITLE
PHP Syntax Highlighter not working

### ISSUE THREAD

**Issue by jhadobe** [adobe/aio-theme#989]
# 🐛 Bug Report 

`php` code blocks in the dev site do not appear to highlight any syntax. 

Here is a page with several `php` code blocks: https://developer.adobe.com/commerce/webapi/get-started/gs-curl/

## 💁 Possible Solution

I suspect a bug in the Prism Syntax Highlighter.

## 💻 Code Sample

Here is a link to the github `.md` page for the file linked above: https://github.com/AdobeDocs/commerce-webapi/blob/main/src/pages/get-started/gs-curl.md?plain=1

## 🧢 Your Company/Team

Developer documentation

Thanks!

**Comment by timkim** [comment]
We'll need to add php support to the prism highlighter. Will be added in the same time as when I do: https://github.com/adobe/aio-theme/issues/1390.

**Comment by timkim** [comment]
Php should now be supported with this commit: 
https://github.com/adobe/aio-theme/commit/3d24836c4476d925b5d458ed06a5bae6a54f42b2

In the theme version 4.9.8 and above.
